config/routes.rb
Rails.application.routes.draw do
  
  root  'home#top'
  get '/new' => 'notes#new'
  get '/list' => 'notes#list'
  post '/notes' => 'notes#create'
  delete '/notes/:id' => 'notes#destroy', as: 'destroy_note'
  

end

app/models/note.rb
class Note < ActiveRecord::Base
    validates :content, presence: true
    validates :income, presence: true
    validates :payment, presence: true
    validates :total, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def top
    end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
    before_action :set_note, only: [:show, :edit, :update, :destroy]
    def new
        @note = Note.new
    end
    def list
        @notes = Note.all
    end
    def create
        @note = Note.new(note_params)
        if @note.save
            redirect_to list_path, notice: "投稿が保存されました"
        else
             render :new
        end
        # @note = Note.new
        # @note.content = params[:content]
        # @note.income = params[:income]
        # @note.payment = params[:payment]
        # @note.total = params[:total]
        # @note.date = params[:date]
        # @note.save
        # redirect_to list_path
    end
    def destroy
        @note = Note.find(params[:id])
        @note.destroy
        redirect_to list_path
    end
   private

    def set_note
      @note = Note.find(params[:id])
    end

    def note_params
      params.require(:note).permit(:content, :income, :payment, :total, :date)
    end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/home/top.html.erb
<h1>俺の家計簿　on Rails</h1>
<div>
    この家計簿はRuby on Railsで作られています\(^^)/
</div>
<!--https://kakeibo-ibuki-konno.c9users.io-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>俺の家計簿</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <header class="navbar">
    <div class="container">
      <div id="logo">俺の家計簿</div>
      <ul class="header-right nav nav-pills">
        <li><%= link_to "トップ", root_path %></li>
        <li><%= link_to "新規投稿", new_path %></li>
        <li><%= link_to "履歴", list_path %></li>
      </ul>
    </div>
  </header>
  <div class = "container">
  <%= yield %>
  </div>
<footer>
  <div class="panel panel-default">
    <div class="panel-footer footer">© 2016 KAKEIBO @AGL</div>
  </div>
</footer>



</body>
</html>

app/views/notes/_form.html.erb
<%= form_for(@note) do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= @note.errors.count %>件のエラーがあります。</h2>

      <ul>
        <% @note.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
    月　日
  <%= f.date_select :date, {use_month_numbers: true},{class: 'form-control date-picker'} %>
  摘　要
    <%= f.text_field :content, { class: "form-control content-field" } %>
  収　入
    <%= f.text_field :income, { class: "form-control income-field" } %>
  支　払
    <%= f.text_field :payment, { class: "form-control payment-field" } %>
  差引残高
    <%= f.text_field :total, { class: "form-control total-field" } %>
  <%= f.submit "投稿する",{class: "btn primary-btn"} %>
<% end %>

app/views/notes/list.html.erb
<h1>履歴</h1>
<table class = "notes">
  <tr>
    <td>月　日</td>
    <td>摘　要</td>
    <td>収　入</td>
    <td>支　払</td>
    <td>差引残高</td>
    <td></td>
  </tr>
  <% @notes.each do |note| %>
  <tr>
      <span class="content">
      <td><%= note.date%></td>
      <td><%= note.content %></td>
      <td><%= note.income %></td>
      <td><%= note.payment %></td>
      <td><%= note.total %></td>
      <td><%= link_to "削除", destroy_note_path(note.id), method: "delete", class: "btn destroy-btn", "data-confirm" => "本当に削除しますか？" %></td>
      </span>
     </tr>
  <% end %>
</table>

app/views/notes/new.html.erb
<h1>新規投稿する</h1>
<%= render 'form' %>